name: StackedItems
main: com.caved_in.stackeditems.StackedItems
version: 1.3.0
description: Utility to sort similar items into specific stack amounts.
author: Brandon Curtis (TheGamersCave)
softdepend: [TagAPI,PopupMenuAPI]
